#!/bin/sh
#
# Copyright (C) Sebastian Philipp
#

set -e

swapsize="$1"
swapname=/swapfile


if [ -z "$swapsize" -o -z "$swapname" ]
then
	cat <<EOF
Usage: $0 <size>

file:      path to the new swap file. This file should not exists.
EOF
	exit 1
fi

if [ -e $swapname ]
then
	echo "error: File already exists. $swapname"
	exit 1
fi


# set NOCOW
touch $swapname
chattr +C $swapname
head -c $swapsize /dev/zero >> $swapname

