#!/bin/sh
#
# Copyright (C) Sebastian Philipp
#

set -e

swapname="$1"


if [ -z "$swapname" ]
then
	cat <<EOF
Usage: $0 <size> <file>

size:      the size of the file, like "8G"
file:      path to the new swap file. This file should not exists.
EOF
	exit 1
fi

swapfile=$(losetup -f) #free loop device

losetup $swapfile $swapname #mount file to loop
mkswap  $swapfile
swapon  $swapfile
